"""
run_scoring.py  —  MTLVerde sustainability scoring, end to end
==============================================================
Reads the team's two JSON files (as committed in the repo's data/ folder),
scores every event, and writes the result with the `id` preserved so seed.py
can load it into Postgres without duplicates.

INPUTS (same folder):
  - public_events_montreal.json   city events (auto-generated by fetch_public_events.py)
  - festivals_montreal.json       curated festivals
  - stops.txt                     STM GTFS stops (from gtfs_stm.zip)
  BIXI is fetched live from GBFS (needs internet).

OUTPUTS:
  - events_scored.json   <- hand this to seed.py / Sarah (keeps `id`)
  - events_scored.csv    <- same, for eyeballing in Excel

Pipeline:
  load both JSONs -> tag source -> filter (online/admin) -> build STM+BIXI
  transit index -> score every row -> save with id preserved.
"""
from __future__ import annotations
import pandas as pd

from mtl_transit_pipeline import load_stm_stops, load_bixi, make_transit_scorer
from sustainability_score import score_event, is_scorable

PUBLIC_EVENTS_JSON = "public_events_montreal.json"
FESTIVALS_JSON     = "festivals_montreal.json"
STM_STOPS          = "stops.txt"
BIXI_SOURCE        = "https://gbfs.velobixi.com/gbfs/2-2/en/station_information.json"
OUT_JSON           = "events_scored.json"
OUT_CSV            = "events_scored.csv"

# `id` FIRST: seed.py needs it as the unique key for Postgres upserts.
DISPLAY_FIELDS = ["id", "titre", "description", "description_en", "url_fiche",
                  "date_debut", "date_fin", "type_evenement", "public_cible",
                  "emplacement", "inscription", "cout", "arrondissement",
                  "adresse_principale", "lat", "long", "source"]
SCORE_FIELDS = ["sustainability_score", "badge", "badge_icon", "eco_flag",
                "free_flag", "score_breakdown", "score_reasons",
                # reported alongside the score, not part of it (see methodology)
                "wheelchair_metro_accessible", "wheelchair_metro_m",
                "wheelchair_metro_gap_m", "wheelchair_note"]


def load_all_events():
    """Both files share an identical 16-column schema, so a plain concat works.
    Their ids don't collide (events = numeric, festivals = slug strings)."""
    events = pd.read_json(PUBLIC_EVENTS_JSON)
    events["source"] = "city"

    festivals = pd.read_json(FESTIVALS_JSON)
    festivals["source"] = "festival"

    combined = pd.concat([events, festivals], ignore_index=True)
    # ids must stay unique across the merged set (seed.py depends on it)
    dupes = combined["id"].duplicated().sum()
    if dupes:
        raise ValueError(f"{dupes} duplicate ids after merge — seed.py would break")
    return combined


def build_transit_index():
    stm = load_stm_stops(STM_STOPS)
    try:
        bixi = load_bixi(BIXI_SOURCE)
    except Exception as e:
        print(f"   ! BIXI feed unavailable ({e}); scoring without the BIXI bonus.")
        bixi = None
    print(f"   STM stops: {len(stm)} (metro={int((stm['is_metro']==1).sum())}, "
          f"bus={int((stm['is_metro']==0).sum())}) | BIXI: {0 if bixi is None else len(bixi)}")
    return make_transit_scorer(stm, bixi)


def main():
    print("1) Loading events + festivals ...")
    df = load_all_events()
    print(f"   {len(df)} rows ({(df['source']=='city').sum()} city, "
          f"{(df['source']=='festival').sum()} festival) | ids unique ✓")

    print("2) Filtering out online + administrative events ...")
    df = df[df.apply(is_scorable, axis=1)].reset_index(drop=True)
    print(f"   {len(df)} events to score")

    print("3) Building transit index (STM + BIXI) ...")
    transit = build_transit_index()

    print("4) Scoring ...")
    results = df.apply(lambda r: score_event(r.to_dict(), transit_index=transit), axis=1)
    scored = pd.concat([df, pd.DataFrame(list(results), index=df.index)], axis=1)

    print("5) Saving ...")
    cols = [c for c in DISPLAY_FIELDS if c in scored.columns] + SCORE_FIELDS
    out = scored[cols]
    out.to_json(OUT_JSON, orient="records", force_ascii=False, indent=2)
    out.to_csv(OUT_CSV, index=False)

    print("\n=== badge distribution ===")
    print(out["badge"].value_counts().to_string())
    print("\n=== score summary ===")
    print(out["sustainability_score"].describe()[["mean","min","25%","50%","75%","max"]].round(1).to_string())
    print(f"\neco_flag: {int(out['eco_flag'].sum())} | free: {int(out['free_flag'].sum())}")
    print(f"\nSaved -> {OUT_JSON} (for seed.py) and {OUT_CSV}")
    return out


if __name__ == "__main__":
    main()
